-- insurer
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO,BIS_RATIO,LITIGATION_RATIO,APPEAL_RATIO,INSURANCE_GUARANTY_FUND,CREDIT_RATING,RETURN_ON_ASSETS,DESCRIPTION2,DESCRIPTION3 ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '51', '臺銀人壽保險公司','臺銀人壽','/resources/pic/保險公司logo/台銀人壽.png','http://www.twfhclife.com.tw/pages/default.aspx','0.9913','2.1293','0.00029','0.0000025','true','twAAA','-0.0062','中華信評：twAAA','標準普爾：A+');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '52', '台灣人壽保險公司','台灣人壽','/resources/pic/保險公司logo/台灣人壽.png','https://www.taiwanlife.com/','0.98');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '53', '保誠人壽保險公司','保誠人壽','/resources/pic/保險公司logo/英國保誠人壽.png','http://www.pcalife.com.tw/corp/prudential_zh_tw/','0.97');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '54', '國泰人壽保險公司','國泰人壽','/resources/pic/保險公司logo/國泰人壽.png','https://www.cathaylife.com.tw/bc/B2CStatic/index.html','0.96');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '55', '中國人壽保險公司','中國人壽','/resources/pic/保險公司logo/中國人壽.png','https://www.hontai.com.tw/09pages/default.aspx','0.95');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '56', '南山人壽保險公司','南山人壽','/resources/pic/保險公司logo/南山人壽.png','https://www.nanshanlife.com.tw/NanshanWeb','0.94');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '58', '新光人壽保險公司','新光人壽','/resources/pic/保險公司logo/新光人壽.png','https://www.skl.com.tw/','0.93');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '65', '英屬百慕達商友邦人壽保險公司','友邦人壽','/resources/pic/保險公司logo/友邦人壽.png','https://www.aia.com.tw/zh-tw/index.html','0.92');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '68', '合作金庫人壽險公司','合庫人壽','/resources/pic/保險公司logo/合作金庫.png','http://www.tcb-life.com.tw/','0.91');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '73', '三商美邦人壽保險公司','三商美邦人壽','/resources/pic/保險公司logo/三商美邦人壽.png','https://www.mli.com.tw/MLI_Public/Default.aspx','0.90');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '77', '英屬曼島商蘇黎世國際人壽','蘇黎世人壽','/resources/pic/保險公司logo/英屬曼島商蘇黎世國際人壽.png','','0.89');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '79', '遠雄人壽保險公司','遠雄人壽','/resources/pic/保險公司logo/遠雄人壽.png','https://www.fglife.com.tw/91dfa8e2f3cd921din092fbd3b9c5d2329bdexbfa817fb6e3549ecomapny_name=fglife','0.79');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '80', '宏泰人壽保險公司','宏泰人壽','/resources/pic/保險公司logo/宏泰人壽.png','https://www.hontai.com.tw/09pages/default.aspx','0.69');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '81', '安聯人壽保險公司','安聯人壽','/resources/pic/保險公司logo/安聯人壽.png','https://www.allianz.com.tw/oneweb/cms/www.allianz.com.tw/zh-tw/','0.59');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '84', '法商法國巴黎人壽保險公司','巴黎人壽','/resources/pic/保險公司logo/法國巴黎.png','https://www.cardif.com.tw/life/','0.49');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '85', '國際康健人壽保險公司','康健人壽','/resources/pic/保險公司logo/康健人壽.png','https://www.cigna.com.tw/','0.39');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '88', '保德信國際人壽保險公司','保德信人壽','/resources/pic/保險公司logo/保德信人壽.png','https://www.prulife.com.tw/page/index.htm','0.29');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '89', '全球人壽保險公司','全球人壽','/resources/pic/保險公司logo/全球人壽.png','http://www.transglobe.com.tw/transglobe-web','0.19');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '91', '元大人壽保險公司','元大人壽','/resources/pic/保險公司logo/元大人壽.png','http://www.yuantalife.com.tw/Web/Index.aspx','0.09');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '92', '中華郵政公司壽險處','中華郵政','/resources/pic/保險公司logo/郵政壽險.png','http://www.post.gov.tw/post/internet/Insurance/','0.08');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '94', '英屬百慕達商安達人壽保險公司','安達人壽','/resources/pic/保險公司logo/英屬百慕達商安達人壽.png','','0.07');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '95', '富邦人壽保險公司','富邦人壽','/resources/pic/保險公司logo/富邦人壽.png','https://www.fubon.com/life/home/index.htm','0.06');
INSERT INTO INSURER (CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, CODE, NAME, SHORT_NAME,IMG_SRC,DESCRIPTION,PERSISTENCY_RATIO ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', '99', '第一金人壽保險公司','第一金人壽','/resources/pic/保險公司logo/第一金人壽.png','https://www.first-aviva.com.tw/','0.95');

--question 
INSERT INTO QUESTION(CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, ASKER_EMAIL, CONTENT, QUESTION_TYPE ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', 'aaa@gmail.com', '測試問題1號', 'ARTICLE');
INSERT INTO QUESTION(CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, ASKER_EMAIL, CONTENT, QUESTION_TYPE ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', 'bbb@gmail.com', '測試問題2號', 'POLICY');
INSERT INTO QUESTION(CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, ASKER_EMAIL, CONTENT, QUESTION_TYPE ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', 'ccc@gmail.com', '測試問題3號', 'CLAIMS');
INSERT INTO QUESTION(CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, ASKER_EMAIL, CONTENT, QUESTION_TYPE ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', 'ddd@gmail.com', '測試問題4號', 'WEBUSE');
INSERT INTO QUESTION(CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, ASKER_EMAIL, CONTENT, QUESTION_TYPE ) VALUES ('SYS', '2017-08-01 00:00:00', 'SYS', '2017-08-01 00:00:00', 'eee@gmail.com', '測試問題5號', 'SALES');
--wishpool
--INSERT INTO WISH (BRAND, NAME, WISH_TIME, WISH_TYPE) VALUES ('統一','7-11','2017/09/04 00:11:37','禮券');
--INSERT INTO WISH (BRAND, NAME, WISH_TIME, WISH_TYPE,WEEK_USE_COUNT) VALUES ('舒適','刮鬍刀','2017/09/03 12:19:55','男仕用品',1);
--INSERT INTO WISH (BRAND, NAME, WISH_TIME, WISH_TYPE,WEEK_USE_COUNT) VALUES ('DYSON','吹風機','2017/09/02 07:43:12','3C家電',1);
--INSERT INTO WISH (CREATED_BY,MODIFIED_BY,BRAND, NAME, WISH_TIME, WISH_TYPE) VALUES ('SYS','SYS','統一','7-11','2017/09/04 00:11:37','禮券');
--INSERT INTO WISH (CREATED_BY,MODIFIED_BY,BRAND, NAME, WISH_TIME, WISH_TYPE) VALUES ('SYS','SYS','舒適','刮鬍刀','2017/09/03 12:19:55','男仕用品');
--INSERT INTO WISH (CREATED_BY,MODIFIED_BY,BRAND, NAME, WISH_TIME, WISH_TYPE) VALUES ('SYS','SYS','DYSON','吹風機','2017/09/02 07:43:12','3C家電');
INSERT INTO WISH (BRAND, NAME, WISH_TIME, WISH_TYPE,WEEK_USE_COUNT) VALUES ('統一','7-11','2017/09/04 00:11:37','禮券',1);
INSERT INTO WISH (BRAND, NAME, WISH_TIME, WISH_TYPE,WEEK_USE_COUNT) VALUES ('舒適','刮鬍刀','2017/09/03 12:19:55','男仕用品',1);
INSERT INTO WISH (BRAND, NAME, WISH_TIME, WISH_TYPE,WEEK_USE_COUNT) VALUES ('DYSON','吹風機','2017/09/02 07:43:12','3C家電',1);
--SECURITY
--USERMEMBER
INSERT INTO USERMEMBER (account_Number, email, name ,password, enabled) VALUES ('user001', 'user001@gmail.com', '測試使用者1號-一般', '$2a$10$puxiUKFbiwV8.EI512uTIu5pHa22lxchelswDjNipVc2khnLfqTMO', true);
INSERT INTO USERMEMBER (account_Number, email, name ,password, enabled) VALUES ('user002', 'user002@gmail.com', '測試使用者2號-下單', '$2a$10$sPgzOU8Atu9cu.rtLYqutOg8OIYpfPTJ8BApXE8R0jGDGC5CpdeiW', true);
INSERT INTO USERMEMBER (account_Number, email, name ,password, enabled) VALUES ('user003', 'user003@gmail.com', '測試使用者3號-工讀', '$2a$10$pGU.Fdw9aIvFArtdglM3K.3.SLwJ2oWKURpYr3BHgl.p.TewtFUWO', true);
INSERT INTO USERMEMBER (account_Number, email, name ,password, enabled) VALUES ('user004', 'user004@gmail.com', '測試使用者4號-業務員', '$2a$10$/XvBLQYpXlvVZoPRPyWNj./lG1J/5bPtLaiOYl.JDRO7YNHkUrUeu', true);
INSERT INTO USERMEMBER (account_Number, email, name ,password, enabled) VALUES ('user005', 'user005@gmail.com', '測試使用者5號-客服', '$2a$10$gPTRoeQ9JkMUuItxaIjZHOTxmkg8WYXpaysL0zfjs3fRzTGKF/egO', true);
INSERT INTO USERMEMBER (account_Number, email, name ,password, enabled) VALUES ('user006', 'user006@gmail.com', '測試使用者6號-文章', '$2a$10$rFOlbE5C/gf4YTTUWJMU2.kMtgTOWEVFeiWOjkzR24xYL4pIgNLae', true);
INSERT INTO USERMEMBER (account_Number, email, name ,password, enabled) VALUES ('user007', 'user007@gmail.com', '測試使用者7號-管理', '$2a$10$B5Zppebjo2RBW5WPuY65H.Nxc45stN0HMjZU4YWVUzVC71j66b4UG', true);
INSERT INTO USERMEMBER (account_Number, email, name ,password, enabled) VALUES ('user008', 'user008@gmail.com', '測試使用者8號-管理', '$2a$10$oc/UifmcXcOup6Cxf6ngxu4z68Yx75ZPbm2BL4LDmssqUQ74tobmm', false);
--ROLE
INSERT INTO ROLE (code, name) VALUES ('ROLE_NORMAL', '一般會員');
INSERT INTO ROLE (code, name) VALUES ('ROLE_ORDER', '下單會員');
INSERT INTO ROLE (code, name) VALUES ('ROLE_PARTTIME', '工讀生');
INSERT INTO ROLE (code, name) VALUES ('ROLE_SALES', '業務員');
INSERT INTO ROLE (code, name) VALUES ('ROLE_SERVICE', '客服人員');
INSERT INTO ROLE (code, name) VALUES ('ROLE_ARTICLE', '文章管理員');
INSERT INTO ROLE (code, name) VALUES ('ROLE_ADMIN', '管理員');
--USER_ROLE
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2,2);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (3,3);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (4,4);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (5,5);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (6,6);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (7,7);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (8,7);

--Article
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('EDITOR_CHOICE','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',true,0,'<p>我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1我是編輯精選1</p>',true,'我是編輯精選1',true,'編輯精選1');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('EDITOR_CHOICE','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',false,0,'<p>我是編輯精選2</p>',true,'我是編輯精選1',true,'編輯精選2');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('EDITOR_CHOICE','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',false,0,'<p></p>',true,'我是編輯精選3',true,'編輯精選3');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('NEWS','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',false,0,'<p></p>',true,'我是新聞專區1',true,'新聞專區1');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('NEWS','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',true,0,'<p></p>',true,'我是新聞專區2',true,'新聞專區2');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('NEWS','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',false,0,'<p></p>',true,'我是新聞專區3',true,'新聞專區3');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('GOODREAD','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',false,0,'<p></p>',true,'我是小資族必讀1',true,'小資族必讀1');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('GOODREAD','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',false,0,'<p></p>',true,'我是小資族必讀2',true,'小資族必讀2');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('GOODREAD','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',true,0,'<p></p>',true,'我是小資族必讀3',true,'小資族必讀3');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('INVESTMENT_TIPS','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',false,0,'<p></p>',true,'我是理財觀念1',true,'理財觀念1');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('INVESTMENT_TIPS','Sarah','/userfiles/bannerImage/09-24_215744tooopen_sy_160022175511.jpg',false,0,'<p></p>',true,'我是理財觀念2',true,'理財觀念2');
INSERT INTO ARTICLE (ARTICLE_TYPE,AUTHOR,BANNER_IMAGE,BANNER_ROTATION,CLICK_COUNT,CONTENT,HOT_ARTICLE,INTRODUCTION,STORE_SHELVES,TITLE) VALUES ('INVESTMENT_TIPS','Sarah','/userfiles/bannerImage/09-24_2359302008070714340350.jpg',false,0,'<p>&nbsp;<span style="color: rgb(0, 0, 255);">台灣大學為了舉辦今年全國大專運動會</span>，<span style="color: rgb(255, 0, 0);">斥資3700萬元修繕國家級認證的田徑場，上周外借給廠商搭建舞台</span>，<span style="background-color: rgb(255, 153, 0);">今天舉辦「中國新歌聲－上海台北音樂節」活動</span>，<u>引發台大生不滿</u>，<em>他們利用網路號召集結抗議。</em><strong>該活動原預定今天下午2時至晚上10時在台大田徑場演出</strong>，<strike>因台大學生號召集結抗議</strike>，到舞台前拉起布條海報抗議，因現場過於混亂，還有抗議學生衝上舞台舉標語，主辦單位在下午約4時40分宣布：「因校方要求及安全因素，結束今天的演出。」</p><p><img src="/userfiles/image/IMG_4985.JPG" width="0" height="0" alt="" /></p><p><a href="/userfiles/image/IMG_4985.JPG"><img src="/userfiles/image/IMG_4985.JPG" width="0" height="0" alt="" /></a></p><p><img src="/userfiles/image/IMG_4985.JPG" width="600" height="358" align="absMiddle" alt="" /><br />抗議學生表示，該活動損毀操場，犧牲學生、教師使用權。有台大學生於《臉書》發起抗議，號召人馬持大聲公等擴音設備、各式相關文宣等進入操場干擾活動，學生下午起在台下按喇叭、灑冥紙干擾表演，隨後也在舞台前拉白布條抗議。活動結束後，抗議學生拿標語布條衝上舞台，高喊「還我操場」、「統戰活動退出校園」等口號，還有獨派人士也到場聲援；另有愛國同心會等團體派員到場鬧場，一度和學生對罵，現場相當混亂。</p>',true,'這是一個圖文並茂的文章',true,'圖文相隔測試');
